=== ewin66/key/Framework/Drectsoft.Core/EmrObjectPersistent/XmlFile/PreDefSqlSentence.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- edited with XMLSpy v2007 (http://www.altova.com) by Wang Yi (DrectSoft) -->
<xs:schema xmlns:DrectSoft="http://www.DrectSoft.com.cn/orm" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.DrectSoft.com.cn/orm" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="PreDefineSqlCollection">
		<xs:annotation>
			<xs:documentation>预定义的查询语句集合</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SelectSentence" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="QuerySentence" type="xs:string">
								<xs:annotation>
									<xs:documentation>不带参数的查询语句</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Name" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>语句标识符</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
					<xs:key name="PKName">
						<xs:selector xpath="SelectSentence"/>
						<xs:field xpath="@Name"/>
					</xs:key>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ewin66/key/Framework/Drectsoft.Core/EmrObjectPersistent/XmlFile/PreDefSqlSentence.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<PreDefineSqlCollection xmlns="http://www.DrectSoft.com.cn/orm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.DrectSoft.com.cn/orm  PreDefSqlSentence.xsd">
  <SelectSentence Name="SelectDepartment">
    <QuerySentence>select ID DeptID,Name DeptName,Py,Wb,HosNo,Sort DeptCatalog,Mark DeptMark,TotalChief,TotalResident,TotalAttend,TotalNurse,TotalBed,TotalExtra,Valid,ADept,BDept,Memo from Department order by Name</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectWard">
    <QuerySentence>select  ID WardID,Name WarkName,Py,Wb,HosNo,TotalBed,Mark WardMark,Valid,Memo from Ward order by Name</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectEmployee">
    <QuerySentence>SELECT ID UserID,Name UserName,Py,Wb,Sexy,Birth,Marital,IDNo,DeptId DeptID,WardID,Category,JobTitle,RecipeID,RecipeMark  ,NarcosisMark,GroupId,Grade,Passwd,JobID,RegDate,Operator,Valid,Memo FROM Users order by Name</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectChargeItem">
    <QuerySentence>SELECT [ItemID],[Name],[Py],[Wb],[BigItem],[Unit],[Format],[Price],[MzBxMark],[ZyBxMark],[ItemCategroy],[Mark],[ItemNature],[ShowMark],[Extra],[UsageScope],[AdviceMark],[Valid],[Memo] FROM [ChargingMinItem]</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectClinicItem">
    <QuerySentence>SELECT [ID],[Name],[HotKeys],[Py],[Wb],[Price],[MasterID],[Valid],[Category],[superID],[Level] FROM [LCChargingItem]</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectTopography">
    <QuerySentence>select a.ID,a.ContentID,a.Name,a.Py,a.Wb,a.Style,b.Name StyleName  from SRTD a,CategoryDetail b where a.ContentID like 'T%' and a.Style=b.ID and a.Status in (2200, 2211)</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectMorphology">
    <QuerySentence>select a.ID,a.ContentID,a.Name,a.Py,a.Wb,a.Style,b.Name StyleName  from SRTD a,CategoryDetail b where a.ContentID like 'M%' and a.Style=b.ID and a.Status in (2200, 2211)  </QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectFunction">
    <QuerySentence>select a.ID,a.ContentID,a.Name,a.Py,a.Wb,a.Style,b.Name StyleName  from SRTD a,CategoryDetail b where a.ContentID like 'F%' and a.Style=b.ID and a.Status in (2200, 2211)  </QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectLivingOrganisms">
    <QuerySentence>select a.ID,a.ContentID,a.Name,a.Py,a.Wb,a.Style,b.Name StyleName  from SRTD a,CategoryDetail b where a.ContentID like 'L%' and a.Style=b.ID and a.Status in (2200, 2211)  </QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectPhysicalAgents">
    <QuerySentence>select a.ID,a.ContentID,a.Name,a.Py,a.Wb,a.Style,b.Name StyleName  from SRTD a,CategoryDetail b where a.ContentID like 'A%' and a.Style=b.ID and a.Status in (2200, 2211)  </QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectSocialContext">
    <QuerySentence>select a.ID,a.ContentID,a.Name,a.Py,a.Wb,a.Style,b.Name StyleName  from SRTD a,CategoryDetail b where a.ContentID like 'S%' and a.Style=b.ID and a.Status in (2200, 2211)  </QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectProcedure">
    <QuerySentence>select a.ID,a.ContentID,a.Name,a.Py,a.Wb,a.Style,b.Name StyleName  from SRTD a,CategoryDetail b where a.ContentID like 'P%' and a.Style=b.ID and a.Status in (2200, 2211)  </QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectGeneralLinkage">
    <QuerySentence>select a.ID,a.ContentID,a.Name,a.Py,a.Wb,a.Style,b.Name StyleName  from SRTD a,CategoryDetail b where a.ContentID like 'G%' and a.Style=b.ID and a.Status in (2200, 2211)  </QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectDruggeryBook">
    <QuerySentence>select a.ID PlaceID,a.FormatID,a.ClinicalID,a.DugName,a.DrugID,a.HotKeys,a.Py,a.Wb,a.Format,a.Dosage DosageID,b.Name Dosage,c.Name ClassDetailName,a.MinUnit,a.FormatUnit,a.Ratio,a.YkUnit,a.YkRatio,a.MzUnit,a.MzRatio,a.ZyUnit,a.ZyRatio,a.EkUnit,a.EkRatio,a.RetailPrice,  a.MzBxMark,a.ZyBxMark,a.DrugNature,a.Specialty,a.OriginID,d.Name Origin, a.Producer,a.AdviceMark,a.UsageScope,a.DrugCategory,a.Valid,a.Memo from PlaceOfDrug a   left join DosageForm b on a.Dosage=b.ID  left join DrugClassDetail c on a.ClassDetail=c.DetailID  left join DrugOrigin d on a.OriginID=d.ID</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectDruggeryCatalogBook">
    <QuerySentence>select  a.DetailID,a.Name,a.Py,a.Wb,a.MasterID ,b.Name ClassName,a.Memo from DrugClassDetail a ,DrugClassify b where a.MasterID=b.ID</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectDruggeryFormBook">
    <QuerySentence>select ID,Name,Py,Wb,Memo from DosageForm</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectDruggerySourceBook">
    <QuerySentence>select ID,Name,Py,Wb,Memo from DrugOrigin</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectOrderUsageBook">
    <QuerySentence>select  ID,Name,Py,Wb,Memo,GroupMark,AutoSort,UseageCategory,Valid from DrugUseage</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectOrderFrequencyBook">
    <QuerySentence>SELECT [ID],[Name],[Py],[Wb],[EXECUTIONS],[ExecuteCycle],[CycleUnit],[ZID],[ExecuteDate],[SelfID],[Mark],[Valid],[Memo]    FROM [AdviceFrequency] order by ID</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectAnesthesiaBook">
    <QuerySentence>SELECT [ID],[MapID],[Name],[Py],[Wb],[Valid],[Memo] FROM [Anesthesia]</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectTumourBook">
    <QuerySentence>SELECT [ID],[MapID],[StandardCode],[Name],[Py],[Wb],[Valid],[Memo] FROM [Tumor]</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectDamnificationBook">
    <QuerySentence>SELECT [ID],[MapID],[StandardCode],[Name],[Py],[Wb],[Valid],[Memo] FROM [Toxicosis]</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectCommonBook">
    <QuerySentence>select a.DetailID,a.MapID,a.CategoryID,a.Name,a.Py,a.Wb,b.Name Category,a.Valid,a.Memo from Dictionary_detail a, Data_Dictionary b where a.CategoryID=b.ID</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectSexBook">
    <QuerySentence>select a.DetailID,a.MapID,a.CategoryID,a.Name,a.Py,a.Wb,b.Name Category,a.Valid,a.Memo from Dictionary_detail a, Data_Dictionary b where a.CategoryID=b.ID and b.ID='3'</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectMetierBook">
    <QuerySentence>select a.DetailID,a.MapID,a.CategoryID,a.Name,a.Py,a.Wb,b.Name Category,a.Valid,a.Memo from Dictionary_detail a, Data_Dictionary b where a.CategoryID=b.ID and b.ID= '41'</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectTechnicalTitleBook">
    <QuerySentence>select a.DetailID,a.MapID,a.CategoryID,a.Name,a.Py,a.Wb,b.Name Category,a.Valid,a.Memo from Dictionary_detail a, Data_Dictionary b where a.CategoryID=b.ID and b.ID='40'</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectRelationBook">
    <QuerySentence>select a.DetailID,a.MapID,a.CategoryID,a.Name,a.Py,a.Wb,b.Name Category,a.Valid,a.Memo from Dictionary_detail a, Data_Dictionary b where a.CategoryID=b.ID and b.ID= '44'</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectTreatResultBook">
    <QuerySentence>select a.DetailID,a.MapID,a.CategoryID,a.Name,a.Py,a.Wb,b.Name Category,a.Valid,a.Memo from Dictionary_detail a, Data_Dictionary b where a.CategoryID=b.ID and b.ID= '8'</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectIncisionLevelBook">
    <QuerySentence>select a.DetailID,a.MapID,a.CategoryID,a.Name,a.Py,a.Wb,b.Name Category,a.Valid,a.Memo from Dictionary_detail a, Data_Dictionary b where a.CategoryID=b.ID and b.ID= '27'</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectCicatrizationKindBook">
    <QuerySentence>select a.DetailID,a.MapID,a.CategoryID,a.Name,a.Py,a.Wb,b.Name Category,a.Valid,a.Memo from Dictionary_detail a, Data_Dictionary b where a.CategoryID=b.ID and b.ID='28'</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectMarriageStateBook">
    <QuerySentence>select a.DetailID,a.MapID,a.CategoryID,a.Name,a.Py,a.Wb,b.Name Category,a.Valid,a.Memo from Dictionary_detail a, Data_Dictionary b where a.CategoryID=b.ID and b.ID= '4'</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectBearStateBook">
    <QuerySentence>select a.DetailID,a.MapID,a.CategoryID,a.Name,a.Py,a.Wb,b.Name Category,a.Valid,a.Memo from Dictionary_detail a, Data_Dictionary b where a.CategoryID=b.ID and b.ID= '51'</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectDiagnoseICD10">
    <QuerySentence>SELECT a.[MarkId],a.[ICD],a.[MapID],a.[StandardCode],a.[Name],a.[Py],a.[Wb],a.[TumorID],b.Name Tumor, a.[Statist],a.[InnerCategory],a.[Category],a.[OtherCategroy],a.[Valid],a.[Memo]    FROM [Diagnosis] a left join Tumor b on a.[TumorID]=b.ID</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectChineseDiagnose">
    <QuerySentence>SELECT ID ChDiagnoseID,MapID,Name,Py,Wb,Valid,Memo,Memo1,Category FROM DiagnosisOfChinese</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectMeasureUnit">
    <QuerySentence>select ID, Name, Py, Wb, Display, UnitCategory, BasicUnit , Rate, Valid, memo from Units</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectDefUsageOfDruggery">
    <QuerySentence>SELECT PlaceID,UsageID,FrequencyID ,Dosage,MinUnit,Days,Mark FROM UsageMapping </QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectDefUsageRangeByDruggeryForm">
    <QuerySentence>SELECT DosageID,UseageID,Memo from Dosage2Useage</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectDepartmentWardMappings">
    <QuerySentence>select DeptID,WardID from Dept2Ward</QuerySentence>
  </SelectSentence>
  <SelectSentence Name="SelectIncisionCicatrizationKindBook">
